#include "world.h"

#define PUBLIC /* empty */
#define PRIVATE static

#define ROCK1 0x00
#define ROCK2 0x01
#define PATH 0x02
#define SFLOWERS 0x03
#define SANDGRASS 0x04
#define GRASS 0x05
#define DIRTGRASS 0x06
#define MFLOWERS 0x07
#define SQPOND 0x08
#define ROISLAND 0x09
#define MROCKS 0x0A
#define SROCKS 0x0B
#define SQISLAND 0x0C
#define LLCORNER 0x0D
#define ULPOND 0x0E
#define MIXFLOWERS 0x0F
#define WFLOWERS 0x10
#define LRCORNER 0x11
#define DSIDE 0x12
#define LRPOND 0x13
#define RSIDE 0x14
#define LSIDE 0x15
#define LLPOND 0x16
#define URPOND 0x17

PRIVATE int tileGrid[20][20] = 
{
    {LSIDE,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,RSIDE},
    {LSIDE,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,MROCKS,SQPOND,GRASS,GRASS,GRASS,GRASS,SQPOND,MROCKS,SANDGRASS,WFLOWERS,WFLOWERS,WFLOWERS,SANDGRASS,WFLOWERS,WFLOWERS,WFLOWERS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,WFLOWERS,DIRTGRASS,WFLOWERS,SANDGRASS,WFLOWERS,WFLOWERS,WFLOWERS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,SQPOND,SANDGRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,SANDGRASS,WFLOWERS,WFLOWERS,WFLOWERS,SANDGRASS,WFLOWERS,WFLOWERS,WFLOWERS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,SANDGRASS,MROCKS,SQPOND,SQPOND,MROCKS,SANDGRASS,GRASS,SANDGRASS,MFLOWERS,MFLOWERS,MFLOWERS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,MIXFLOWERS,ROCK1,ROCK2,ROCK1,MIXFLOWERS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,GRASS,SANDGRASS,MFLOWERS,SQPOND,MFLOWERS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,SANDGRASS, MIXFLOWERS, MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,SANDGRASS,GRASS,SANDGRASS,MFLOWERS,SQPOND,MFLOWERS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS, MIXFLOWERS,ULPOND,URPOND,MIXFLOWERS,SANDGRASS,GRASS,SANDGRASS,MFLOWERS,MFLOWERS,MFLOWERS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,WFLOWERS,WFLOWERS,WFLOWERS,WFLOWERS,WFLOWERS,SANDGRASS,MIXFLOWERS,LLPOND,LRPOND,MIXFLOWERS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,WFLOWERS,WFLOWERS,WFLOWERS,WFLOWERS,WFLOWERS,SANDGRASS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,SANDGRASS,SFLOWERS,SFLOWERS,SFLOWERS,SANDGRASS,GRASS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SFLOWERS,SFLOWERS,SFLOWERS,SANDGRASS,GRASS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,MFLOWERS,MFLOWERS,MFLOWERS,MFLOWERS,MFLOWERS,MFLOWERS,SANDGRASS,SQPOND,SQPOND,SANDGRASS,SFLOWERS,MFLOWERS,SFLOWERS,SFLOWERS,SANDGRASS,SANDGRASS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,MFLOWERS,MFLOWERS,GRASS,GRASS,MFLOWERS,MFLOWERS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SFLOWERS,SFLOWERS,SFLOWERS,SFLOWERS,SANDGRASS,SQPOND,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,MFLOWERS,MFLOWERS,MFLOWERS,MFLOWERS,MFLOWERS,MFLOWERS,SANDGRASS,ROCK2,ROCK1,SANDGRASS,SFLOWERS,SFLOWERS,SFLOWERS,SFLOWERS,SANDGRASS,SQPOND,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,SANDGRASS,SQPOND,SQPOND,SANDGRASS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,MIXFLOWERS,SANDGRASS,RSIDE},
    {LSIDE,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,SANDGRASS,RSIDE},
    {LLCORNER,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,DSIDE,LRCORNER}
};
    
PRIVATE int TILE_ROWS = 20;
PRIVATE int TILE_COLUMNS = 20;
PRIVATE int TILE_WIDTH = 32;
PRIVATE int TILE_HEIGHT = 32;

PUBLIC int getTileRows(){
    return TILE_ROWS;
}

PUBLIC int getTileColumns(){
    return TILE_COLUMNS;
}

PUBLIC int getTileWidth(){
    return TILE_WIDTH;
}

PUBLIC int getTileHeight(){
    return TILE_HEIGHT;
}

PUBLIC int getTileGrid(int x, int y){
    return tileGrid[x][y];
}

//TRÄD
PRIVATE int NR_OF_TREES = 12; 
PRIVATE int TREE_WIDTH = 32;
PRIVATE int TREE_HEIGHT = 47;

PRIVATE int treeCoordinates[12][2] = {
    //FOUR TREES IN THE MIDDLE OF THE WORLD
    {252, 233}, //LEFT CORNER (TOP)
    {252, 341}, //LEFT CORNER (BOTTOM)
    {356, 233}, //RIGHT CORNER (TOP)
    {352, 341}, //RIGHT CORNER (BOTTOM)

    {385,85},  //TREE SURROUNDED BY WHITE FLOWER

    //FOUR TREES AT THE TOP
    {130,45},
    {160,45},
    {190,45},
    {220,45},

    //TREES BY FLOWER FIELD
    {442,402},

    //TREES BY DIRT
    {130, 430},
    {160, 430}
};

PUBLIC int getNrOfTrees(){
    return NR_OF_TREES;
}

PUBLIC int getTreeWidth(){
    return TREE_WIDTH;
}

PUBLIC int getTreeHeight(){
    return TREE_HEIGHT;
}

PUBLIC int getTreeX(int i){
    return treeCoordinates[i][0];
}

PUBLIC int getTreeY(int i){
    return treeCoordinates[i][1];
}

//BUSHES
PRIVATE int NR_OF_BUSHES = 44; 
PRIVATE int BUSH_WIDTH = 16;
PRIVATE int BUSH_HEIGHT = 16;

PRIVATE int bushCoordinates[44][2] = {
    //FIVE BUSHES ROW 11
    {73,345},
    {103,345},
    {133,345},
    {163,345},
    {193, 345},

    //UPPER RIGHT CORNER OF THE GAME 
    {475,60}, //row 1
    {505,60},
    {533,60},
    {562, 60},

    {475,100}, //row 2
    {505,100},
    {533,100},
    {562, 100},

    {475,148}, //row 3
    {505,148},
    {533,148},
    {562, 148},

    //SIX BUSHES ROW 5
    {137,137}, 
    {168,137},
    {200,137},
    {232,137},
    {264, 137},
    {296, 137},

    //TWO BUSHES
    {424,264},
    {424,232},

    //THE BUSHES SURROUNDED BY PONDS 
    {552, 393},
    {552, 361},

    //THE BUSHES AROUND THE TREES
    {417,350},
    {458,350},
    {496,350},

    {383,497},
    {417,497},
    {454,497},
    {496,497},

    {383,457},
    {383,417},

    {417,392},
    
    {496,393},
    {496,450},

    //BUSHES BY THE TREE
    {110, 455},
    
    {185, 465},
    {152, 472},
    {120, 465},
    {195, 455},
};

PUBLIC int getNrOfBushes(){
    return NR_OF_BUSHES;
}

PUBLIC int getBushWidth(){
    return BUSH_WIDTH;
}

PUBLIC int getBushHeight(){
    return BUSH_HEIGHT;
}

PUBLIC int getBushX(int i){
    return bushCoordinates[i][0];
}

PUBLIC int getBushY(int i){
    return bushCoordinates[i][1];
}